Repository MontyTRC89/Tomb-Editor, pull requests merged in 2023-12, with the labels that each got.

#747 Removal of Tomb5Main references
  TombLib/TombLib/Catalogs/Engines/TR1/Moveables.xml
  TombLib/TombLib/Catalogs/Engines/TR1/Sounds.xml
  TombLib/TombLib/Catalogs/Engines/TR2/Moveables.xml
  TombLib/TombLib/Catalogs/Engines/TR2/Sounds.xml
  TombLib/TombLib/Catalogs/Engines/TR3/Moveables.xml
  TombLib/TombLib/Catalogs/Engines/TR3/Sounds.xml
  TombLib/TombLib/Catalogs/Engines/TR4/Moveables.xml
  TombLib/TombLib/Catalogs/Engines/TR4/Sounds.xml
  TombLib/TombLib/Catalogs/Engines/TR5/Moveables.xml
  TombLib/TombLib/Catalogs/Engines/TR5/Sounds.xml
  TombLib/TombLib/Catalogs/Engines/TR5/SpriteSequences.xml
  TombLib/TombLib/Catalogs/Engines/TombEngine/Sounds.xml
  TombLib/TombLib/LevelData/Compilers/Structs.cs
  TombLib/TombLib/Wad/Catalog/TrCatalog.cs
Labels: legacy

#732 More vertical subdivisions + RoomGeometry code overhaul
  TombEditor/Command.cs
  TombEditor/Controls/Panel3D/MouseHandler/Panel3DMouseMove.cs
  TombEditor/Controls/Panel3D/Panel3D.cs
  TombEditor/Controls/Panel3D/Panel3DDraw.cs
  TombEditor/Controls/Panel3D/Panel3DPicking.cs
  TombEditor/Controls/Panel3D/ToolHandler.cs
  TombEditor/EditorActions.cs
  TombEditor/Forms/FormTextureRemap.cs
  TombEditor/SectorsClipboardData.cs
  TombLib/TombLib.Rendering/Rendering/SectorTextures.cs
  TombLib/TombLib/GeometryIO/RoomGeometryExporter.cs
  TombLib/TombLib/LevelData/Block.cs
  TombLib/TombLib/LevelData/Compilers/Rooms.cs
  TombLib/TombLib/LevelData/Compilers/Textures.cs
  TombLib/TombLib/LevelData/Compilers/TombEngine/Rooms.cs
  TombLib/TombLib/LevelData/Compilers/TombEngine/Textures.cs
  TombLib/TombLib/LevelData/IO/Prj2Chunks.cs
  TombLib/TombLib/LevelData/IO/Prj2Loader.cs
  TombLib/TombLib/LevelData/IO/Prj2Writer.cs
  TombLib/TombLib/LevelData/IO/PrjLoader.cs
  TombLib/TombLib/LevelData/Level.cs
  TombLib/TombLib/LevelData/Room.cs
  TombLib/TombLib/LevelData/RoomGeometry.cs
  TombLib/TombLib/Utils/RectTransformation.cs
  TombLib/TombLib/Utils/Swap.cs
Labels: enhancement, new feature, high priority, refactoring

#751 Set Post-Process Display Node
  TombLib/TombLib/Catalogs/TEN Node Catalogs/Effects.lua
  TombLib/TombLib/Catalogs/TEN Node Catalogs/View.lua
  TombLib/TombLib/Catalogs/TEN Node Catalogs/_System.lua
Labels: enhancement
